// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branch.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countBranches = `-- name: CountBranches :one
SELECT count(*) FROM branches
`

func (q *Queries) CountBranches(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBranches)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (name, address, phone)
VALUES ($1, $2, $3)
RETURNING id, name, address, phone, active, created_at, updated_at
`

type CreateBranchParams struct {
	Name    string `json:"name"`
	Address string `json:"address"`
	Phone   string `json:"phone"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch, arg.Name, arg.Address, arg.Phone)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBranch = `-- name: GetBranch :one
SELECT id, name, address, phone, active, created_at, updated_at FROM branches WHERE id = $1
`

func (q *Queries) GetBranch(ctx context.Context, id uuid.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranch, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
SELECT id, name, address, phone, active, created_at, updated_at FROM branches
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListBranchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches
SET name = $2, address = $3, phone = $4, active = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, address, phone, active, created_at, updated_at
`

type UpdateBranchParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Address string    `json:"address"`
	Phone   string    `json:"phone"`
	Active  bool      `json:"active"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
		arg.Active,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
