// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package store

import (
	"context"
	"time"
)

const now = `-- name: Now :one
SELECT now()::timestamptz AS current_time
`

// A trivial query used to verify database connectivity and the query pipeline.
func (q *Queries) Now(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, now)
	var current_time time.Time
	err := row.Scan(&current_time)
	return current_time, err
}
