// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const adjustBatchQuantity = `-- name: AdjustBatchQuantity :one
UPDATE stock_batches
SET quantity = quantity + $1
WHERE id = $2 AND quantity + $1 >= 0
RETURNING id, product_id, branch_id, batch_no, quantity, cost_price, sale_price, expiry_date, received_at
`

type AdjustBatchQuantityParams struct {
	Delta int32     `json:"delta"`
	ID    uuid.UUID `json:"id"`
}

// Apply a signed delta to a batch, refusing to drive quantity negative.
// Zero rows returned means the adjustment would go below zero.
func (q *Queries) AdjustBatchQuantity(ctx context.Context, arg AdjustBatchQuantityParams) (StockBatch, error) {
	row := q.db.QueryRow(ctx, adjustBatchQuantity, arg.Delta, arg.ID)
	var i StockBatch
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.BatchNo,
		&i.Quantity,
		&i.CostPrice,
		&i.SalePrice,
		&i.ExpiryDate,
		&i.ReceivedAt,
	)
	return i, err
}

const countBranchBatches = `-- name: CountBranchBatches :one
SELECT count(*) FROM stock_batches
WHERE branch_id = $1 AND quantity > 0
`

func (q *Queries) CountBranchBatches(ctx context.Context, branchID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBranchBatches, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStockMovements = `-- name: CountStockMovements :one
SELECT count(*) FROM stock_movements
WHERE branch_id = $1
  AND ($2::uuid IS NULL OR product_id = $2)
`

type CountStockMovementsParams struct {
	BranchID  uuid.UUID  `json:"branch_id"`
	ProductID *uuid.UUID `json:"product_id"`
}

func (q *Queries) CountStockMovements(ctx context.Context, arg CountStockMovementsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStockMovements, arg.BranchID, arg.ProductID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStockBatch = `-- name: CreateStockBatch :one

INSERT INTO stock_batches (
    product_id, branch_id, batch_no, quantity, cost_price, sale_price, expiry_date
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, product_id, branch_id, batch_no, quantity, cost_price, sale_price, expiry_date, received_at
`

type CreateStockBatchParams struct {
	ProductID  uuid.UUID       `json:"product_id"`
	BranchID   uuid.UUID       `json:"branch_id"`
	BatchNo    string          `json:"batch_no"`
	Quantity   int32           `json:"quantity"`
	CostPrice  decimal.Decimal `json:"cost_price"`
	SalePrice  decimal.Decimal `json:"sale_price"`
	ExpiryDate time.Time       `json:"expiry_date"`
}

// Inventory write queries. Batches and the movement ledger are written by the
// purchasing (goods-received) and sales (dispensing) flows inside a transaction.
func (q *Queries) CreateStockBatch(ctx context.Context, arg CreateStockBatchParams) (StockBatch, error) {
	row := q.db.QueryRow(ctx, createStockBatch,
		arg.ProductID,
		arg.BranchID,
		arg.BatchNo,
		arg.Quantity,
		arg.CostPrice,
		arg.SalePrice,
		arg.ExpiryDate,
	)
	var i StockBatch
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.BatchNo,
		&i.Quantity,
		&i.CostPrice,
		&i.SalePrice,
		&i.ExpiryDate,
		&i.ReceivedAt,
	)
	return i, err
}

const decrementBatchQuantity = `-- name: DecrementBatchQuantity :one
UPDATE stock_batches
SET quantity = quantity - $1
WHERE id = $2 AND quantity >= $1
RETURNING id, product_id, branch_id, batch_no, quantity, cost_price, sale_price, expiry_date, received_at
`

type DecrementBatchQuantityParams struct {
	Qty int32     `json:"qty"`
	ID  uuid.UUID `json:"id"`
}

// Decrement a batch's quantity, but only if enough remains. Returns the updated
// row; zero rows means insufficient stock (used by FEFO dispensing).
func (q *Queries) DecrementBatchQuantity(ctx context.Context, arg DecrementBatchQuantityParams) (StockBatch, error) {
	row := q.db.QueryRow(ctx, decrementBatchQuantity, arg.Qty, arg.ID)
	var i StockBatch
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.BatchNo,
		&i.Quantity,
		&i.CostPrice,
		&i.SalePrice,
		&i.ExpiryDate,
		&i.ReceivedAt,
	)
	return i, err
}

const getStockBatch = `-- name: GetStockBatch :one

SELECT id, product_id, branch_id, batch_no, quantity, cost_price, sale_price, expiry_date, received_at FROM stock_batches WHERE id = $1
`

// Stock adjustment / return writes and the movement-ledger view ---------------
func (q *Queries) GetStockBatch(ctx context.Context, id uuid.UUID) (StockBatch, error) {
	row := q.db.QueryRow(ctx, getStockBatch, id)
	var i StockBatch
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.BatchNo,
		&i.Quantity,
		&i.CostPrice,
		&i.SalePrice,
		&i.ExpiryDate,
		&i.ReceivedAt,
	)
	return i, err
}

const listBranchBatches = `-- name: ListBranchBatches :many

SELECT sb.id, sb.product_id, sb.branch_id, sb.batch_no, sb.quantity, sb.cost_price, sb.sale_price, sb.expiry_date, sb.received_at, p.name AS product_name
FROM stock_batches sb
JOIN products p ON p.id = sb.product_id
WHERE sb.branch_id = $1 AND sb.quantity > 0
ORDER BY sb.expiry_date ASC
LIMIT $2 OFFSET $3
`

type ListBranchBatchesParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type ListBranchBatchesRow struct {
	ID          uuid.UUID       `json:"id"`
	ProductID   uuid.UUID       `json:"product_id"`
	BranchID    uuid.UUID       `json:"branch_id"`
	BatchNo     string          `json:"batch_no"`
	Quantity    int32           `json:"quantity"`
	CostPrice   decimal.Decimal `json:"cost_price"`
	SalePrice   decimal.Decimal `json:"sale_price"`
	ExpiryDate  time.Time       `json:"expiry_date"`
	ReceivedAt  time.Time       `json:"received_at"`
	ProductName string          `json:"product_name"`
}

// Inventory read queries (per-branch stock, expiry & reorder alerts) ----------
func (q *Queries) ListBranchBatches(ctx context.Context, arg ListBranchBatchesParams) ([]ListBranchBatchesRow, error) {
	rows, err := q.db.Query(ctx, listBranchBatches, arg.BranchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchBatchesRow{}
	for rows.Next() {
		var i ListBranchBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BranchID,
			&i.BatchNo,
			&i.Quantity,
			&i.CostPrice,
			&i.SalePrice,
			&i.ExpiryDate,
			&i.ReceivedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDispensableBatches = `-- name: ListDispensableBatches :many
SELECT id, product_id, branch_id, batch_no, quantity, cost_price, sale_price, expiry_date, received_at FROM stock_batches
WHERE branch_id = $1 AND product_id = $2
  AND quantity > 0 AND expiry_date >= CURRENT_DATE
ORDER BY expiry_date ASC
FOR UPDATE
`

type ListDispensableBatchesParams struct {
	BranchID  uuid.UUID `json:"branch_id"`
	ProductID uuid.UUID `json:"product_id"`
}

// FEFO: batches with stock for a product at a branch, earliest expiry first,
// skipping already-expired stock. Locked FOR UPDATE so concurrent sales cannot
// oversell the same batch.
func (q *Queries) ListDispensableBatches(ctx context.Context, arg ListDispensableBatchesParams) ([]StockBatch, error) {
	rows, err := q.db.Query(ctx, listDispensableBatches, arg.BranchID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StockBatch{}
	for rows.Next() {
		var i StockBatch
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BranchID,
			&i.BatchNo,
			&i.Quantity,
			&i.CostPrice,
			&i.SalePrice,
			&i.ExpiryDate,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLowStock = `-- name: ListLowStock :many
SELECT p.id AS product_id, p.name AS product_name, p.reorder_level,
       COALESCE(SUM(sb.quantity), 0)::bigint AS on_hand
FROM products p
LEFT JOIN stock_batches sb
    ON sb.product_id = p.id AND sb.branch_id = $1
WHERE p.active
GROUP BY p.id
HAVING COALESCE(SUM(sb.quantity), 0) <= p.reorder_level
ORDER BY on_hand ASC
`

type ListLowStockRow struct {
	ProductID    uuid.UUID `json:"product_id"`
	ProductName  string    `json:"product_name"`
	ReorderLevel int32     `json:"reorder_level"`
	OnHand       int64     `json:"on_hand"`
}

func (q *Queries) ListLowStock(ctx context.Context, branchID uuid.UUID) ([]ListLowStockRow, error) {
	rows, err := q.db.Query(ctx, listLowStock, branchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLowStockRow{}
	for rows.Next() {
		var i ListLowStockRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.ReorderLevel,
			&i.OnHand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNearExpiryBatches = `-- name: ListNearExpiryBatches :many
SELECT sb.id, sb.product_id, sb.branch_id, sb.batch_no, sb.quantity, sb.cost_price, sb.sale_price, sb.expiry_date, sb.received_at, p.name AS product_name
FROM stock_batches sb
JOIN products p ON p.id = sb.product_id
WHERE sb.branch_id = $1
  AND sb.quantity > 0
  AND sb.expiry_date <= CURRENT_DATE + ($2::int)
ORDER BY sb.expiry_date ASC
`

type ListNearExpiryBatchesParams struct {
	BranchID   uuid.UUID `json:"branch_id"`
	WithinDays int32     `json:"within_days"`
}

type ListNearExpiryBatchesRow struct {
	ID          uuid.UUID       `json:"id"`
	ProductID   uuid.UUID       `json:"product_id"`
	BranchID    uuid.UUID       `json:"branch_id"`
	BatchNo     string          `json:"batch_no"`
	Quantity    int32           `json:"quantity"`
	CostPrice   decimal.Decimal `json:"cost_price"`
	SalePrice   decimal.Decimal `json:"sale_price"`
	ExpiryDate  time.Time       `json:"expiry_date"`
	ReceivedAt  time.Time       `json:"received_at"`
	ProductName string          `json:"product_name"`
}

func (q *Queries) ListNearExpiryBatches(ctx context.Context, arg ListNearExpiryBatchesParams) ([]ListNearExpiryBatchesRow, error) {
	rows, err := q.db.Query(ctx, listNearExpiryBatches, arg.BranchID, arg.WithinDays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListNearExpiryBatchesRow{}
	for rows.Next() {
		var i ListNearExpiryBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BranchID,
			&i.BatchNo,
			&i.Quantity,
			&i.CostPrice,
			&i.SalePrice,
			&i.ExpiryDate,
			&i.ReceivedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT sm.id, sm.product_id, sm.branch_id, sm.batch_id, sm.type, sm.qty, sm.ref_type, sm.ref_id, sm.note, sm.created_at, p.name AS product_name
FROM stock_movements sm
JOIN products p ON p.id = sm.product_id
WHERE sm.branch_id = $1
  AND ($2::uuid IS NULL OR sm.product_id = $2)
ORDER BY sm.created_at DESC
LIMIT $4 OFFSET $3
`

type ListStockMovementsParams struct {
	BranchID  uuid.UUID  `json:"branch_id"`
	ProductID *uuid.UUID `json:"product_id"`
	Offset    int32      `json:"offset"`
	Limit     int32      `json:"limit"`
}

type ListStockMovementsRow struct {
	ID          uuid.UUID    `json:"id"`
	ProductID   uuid.UUID    `json:"product_id"`
	BranchID    uuid.UUID    `json:"branch_id"`
	BatchID     *uuid.UUID   `json:"batch_id"`
	Type        MovementType `json:"type"`
	Qty         int32        `json:"qty"`
	RefType     string       `json:"ref_type"`
	RefID       *uuid.UUID   `json:"ref_id"`
	Note        string       `json:"note"`
	CreatedAt   time.Time    `json:"created_at"`
	ProductName string       `json:"product_name"`
}

func (q *Queries) ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]ListStockMovementsRow, error) {
	rows, err := q.db.Query(ctx, listStockMovements,
		arg.BranchID,
		arg.ProductID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockMovementsRow{}
	for rows.Next() {
		var i ListStockMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BranchID,
			&i.BatchID,
			&i.Type,
			&i.Qty,
			&i.RefType,
			&i.RefID,
			&i.Note,
			&i.CreatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordStockMovement = `-- name: RecordStockMovement :one
INSERT INTO stock_movements (
    product_id, branch_id, batch_id, type, qty, ref_type, ref_id, note
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, product_id, branch_id, batch_id, type, qty, ref_type, ref_id, note, created_at
`

type RecordStockMovementParams struct {
	ProductID uuid.UUID    `json:"product_id"`
	BranchID  uuid.UUID    `json:"branch_id"`
	BatchID   *uuid.UUID   `json:"batch_id"`
	Type      MovementType `json:"type"`
	Qty       int32        `json:"qty"`
	RefType   string       `json:"ref_type"`
	RefID     *uuid.UUID   `json:"ref_id"`
	Note      string       `json:"note"`
}

func (q *Queries) RecordStockMovement(ctx context.Context, arg RecordStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, recordStockMovement,
		arg.ProductID,
		arg.BranchID,
		arg.BatchID,
		arg.Type,
		arg.Qty,
		arg.RefType,
		arg.RefID,
		arg.Note,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.BatchID,
		&i.Type,
		&i.Qty,
		&i.RefType,
		&i.RefID,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const setBatchQuantity = `-- name: SetBatchQuantity :one
WITH locked AS (
    SELECT sb.id, sb.quantity AS prev
    FROM stock_batches sb
    WHERE sb.id = $2
    FOR UPDATE
)
UPDATE stock_batches sb
SET quantity = $1
FROM locked
WHERE sb.id = locked.id
RETURNING sb.id, sb.product_id, sb.branch_id, sb.batch_no, sb.quantity, sb.cost_price, sb.sale_price, sb.expiry_date, sb.received_at, locked.prev AS previous_quantity
`

type SetBatchQuantityParams struct {
	Quantity int32     `json:"quantity"`
	ID       uuid.UUID `json:"id"`
}

type SetBatchQuantityRow struct {
	ID               uuid.UUID       `json:"id"`
	ProductID        uuid.UUID       `json:"product_id"`
	BranchID         uuid.UUID       `json:"branch_id"`
	BatchNo          string          `json:"batch_no"`
	Quantity         int32           `json:"quantity"`
	CostPrice        decimal.Decimal `json:"cost_price"`
	SalePrice        decimal.Decimal `json:"sale_price"`
	ExpiryDate       time.Time       `json:"expiry_date"`
	ReceivedAt       time.Time       `json:"received_at"`
	PreviousQuantity int32           `json:"previous_quantity"`
}

// Set a batch to an absolute counted quantity (physical stock-take), locking the
// row and returning both the new row and the previous quantity so the caller can
// record the delta as an adjustment movement.
func (q *Queries) SetBatchQuantity(ctx context.Context, arg SetBatchQuantityParams) (SetBatchQuantityRow, error) {
	row := q.db.QueryRow(ctx, setBatchQuantity, arg.Quantity, arg.ID)
	var i SetBatchQuantityRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BranchID,
		&i.BatchNo,
		&i.Quantity,
		&i.CostPrice,
		&i.SalePrice,
		&i.ExpiryDate,
		&i.ReceivedAt,
		&i.PreviousQuantity,
	)
	return i, err
}

const stockOnHand = `-- name: StockOnHand :one
SELECT COALESCE(SUM(quantity), 0)::bigint AS on_hand
FROM stock_batches
WHERE branch_id = $1 AND product_id = $2
`

type StockOnHandParams struct {
	BranchID  uuid.UUID `json:"branch_id"`
	ProductID uuid.UUID `json:"product_id"`
}

func (q *Queries) StockOnHand(ctx context.Context, arg StockOnHandParams) (int64, error) {
	row := q.db.QueryRow(ctx, stockOnHand, arg.BranchID, arg.ProductID)
	var on_hand int64
	err := row.Scan(&on_hand)
	return on_hand, err
}
