// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type MovementType string

const (
	MovementTypePurchase    MovementType = "purchase"
	MovementTypeSale        MovementType = "sale"
	MovementTypeAdjustment  MovementType = "adjustment"
	MovementTypeReturn      MovementType = "return"
	MovementTypeTransferOut MovementType = "transfer_out"
	MovementTypeTransferIn  MovementType = "transfer_in"
)

func (e *MovementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MovementType(s)
	case string:
		*e = MovementType(s)
	default:
		return fmt.Errorf("unsupported scan type for MovementType: %T", src)
	}
	return nil
}

type NullMovementType struct {
	MovementType MovementType `json:"movement_type"`
	Valid        bool         `json:"valid"` // Valid is true if MovementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMovementType) Scan(value interface{}) error {
	if value == nil {
		ns.MovementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MovementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMovementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MovementType), nil
}

type PaymentMethod string

const (
	PaymentMethodCash   PaymentMethod = "cash"
	PaymentMethodCard   PaymentMethod = "card"
	PaymentMethodMobile PaymentMethod = "mobile"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod `json:"payment_method"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PoStatus string

const (
	PoStatusDraft     PoStatus = "draft"
	PoStatusOrdered   PoStatus = "ordered"
	PoStatusReceived  PoStatus = "received"
	PoStatusCancelled PoStatus = "cancelled"
)

func (e *PoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PoStatus(s)
	case string:
		*e = PoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PoStatus: %T", src)
	}
	return nil
}

type NullPoStatus struct {
	PoStatus PoStatus `json:"po_status"`
	Valid    bool     `json:"valid"` // Valid is true if PoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PoStatus), nil
}

type UserRole string

const (
	UserRoleAdmin      UserRole = "admin"
	UserRoleManager    UserRole = "manager"
	UserRolePharmacist UserRole = "pharmacist"
	UserRoleCashier    UserRole = "cashier"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Branch struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Address   string    `json:"address"`
	Phone     string    `json:"phone"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Customer struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Phone     string    `json:"phone"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Prescription struct {
	ID          uuid.UUID  `json:"id"`
	CustomerID  uuid.UUID  `json:"customer_id"`
	BranchID    uuid.UUID  `json:"branch_id"`
	DoctorName  string     `json:"doctor_name"`
	Notes       string     `json:"notes"`
	DispensedAt *time.Time `json:"dispensed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type PrescriptionItem struct {
	ID             uuid.UUID `json:"id"`
	PrescriptionID uuid.UUID `json:"prescription_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Qty            int32     `json:"qty"`
	Dosage         string    `json:"dosage"`
}

type Product struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	GenericName  string    `json:"generic_name"`
	Form         string    `json:"form"`
	Strength     string    `json:"strength"`
	Barcode      *string   `json:"barcode"`
	Category     string    `json:"category"`
	Unit         string    `json:"unit"`
	ReorderLevel int32     `json:"reorder_level"`
	Active       bool      `json:"active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type PurchaseOrder struct {
	ID         uuid.UUID  `json:"id"`
	BranchID   uuid.UUID  `json:"branch_id"`
	SupplierID uuid.UUID  `json:"supplier_id"`
	Status     PoStatus   `json:"status"`
	Reference  string     `json:"reference"`
	OrderedAt  *time.Time `json:"ordered_at"`
	ReceivedAt *time.Time `json:"received_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type PurchaseOrderItem struct {
	ID        uuid.UUID       `json:"id"`
	PoID      uuid.UUID       `json:"po_id"`
	ProductID uuid.UUID       `json:"product_id"`
	Qty       int32           `json:"qty"`
	UnitCost  decimal.Decimal `json:"unit_cost"`
}

type Sale struct {
	ID             uuid.UUID       `json:"id"`
	BranchID       uuid.UUID       `json:"branch_id"`
	CashierID      uuid.UUID       `json:"cashier_id"`
	CustomerID     *uuid.UUID      `json:"customer_id"`
	PrescriptionID *uuid.UUID      `json:"prescription_id"`
	Subtotal       decimal.Decimal `json:"subtotal"`
	Discount       decimal.Decimal `json:"discount"`
	Total          decimal.Decimal `json:"total"`
	Paid           decimal.Decimal `json:"paid"`
	PaymentMethod  PaymentMethod   `json:"payment_method"`
	CreatedAt      time.Time       `json:"created_at"`
}

type SaleItem struct {
	ID        uuid.UUID       `json:"id"`
	SaleID    uuid.UUID       `json:"sale_id"`
	BatchID   uuid.UUID       `json:"batch_id"`
	ProductID uuid.UUID       `json:"product_id"`
	Qty       int32           `json:"qty"`
	UnitPrice decimal.Decimal `json:"unit_price"`
}

type StockBatch struct {
	ID         uuid.UUID       `json:"id"`
	ProductID  uuid.UUID       `json:"product_id"`
	BranchID   uuid.UUID       `json:"branch_id"`
	BatchNo    string          `json:"batch_no"`
	Quantity   int32           `json:"quantity"`
	CostPrice  decimal.Decimal `json:"cost_price"`
	SalePrice  decimal.Decimal `json:"sale_price"`
	ExpiryDate time.Time       `json:"expiry_date"`
	ReceivedAt time.Time       `json:"received_at"`
}

type StockMovement struct {
	ID        uuid.UUID    `json:"id"`
	ProductID uuid.UUID    `json:"product_id"`
	BranchID  uuid.UUID    `json:"branch_id"`
	BatchID   *uuid.UUID   `json:"batch_id"`
	Type      MovementType `json:"type"`
	Qty       int32        `json:"qty"`
	RefType   string       `json:"ref_type"`
	RefID     *uuid.UUID   `json:"ref_id"`
	Note      string       `json:"note"`
	CreatedAt time.Time    `json:"created_at"`
	CreatedBy *uuid.UUID   `json:"created_by"`
}

type Supplier struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Contact   string    `json:"contact"`
	Phone     string    `json:"phone"`
	Email     string    `json:"email"`
	Active    bool      `json:"active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID  `json:"id"`
	Email        string     `json:"email"`
	PasswordHash string     `json:"password_hash"`
	FullName     string     `json:"full_name"`
	Role         UserRole   `json:"role"`
	BranchID     *uuid.UUID `json:"branch_id"`
	Active       bool       `json:"active"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}
