// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prescription.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const addPrescriptionItem = `-- name: AddPrescriptionItem :one
INSERT INTO prescription_items (prescription_id, product_id, qty, dosage)
VALUES ($1, $2, $3, $4)
RETURNING id, prescription_id, product_id, qty, dosage
`

type AddPrescriptionItemParams struct {
	PrescriptionID uuid.UUID `json:"prescription_id"`
	ProductID      uuid.UUID `json:"product_id"`
	Qty            int32     `json:"qty"`
	Dosage         string    `json:"dosage"`
}

func (q *Queries) AddPrescriptionItem(ctx context.Context, arg AddPrescriptionItemParams) (PrescriptionItem, error) {
	row := q.db.QueryRow(ctx, addPrescriptionItem,
		arg.PrescriptionID,
		arg.ProductID,
		arg.Qty,
		arg.Dosage,
	)
	var i PrescriptionItem
	err := row.Scan(
		&i.ID,
		&i.PrescriptionID,
		&i.ProductID,
		&i.Qty,
		&i.Dosage,
	)
	return i, err
}

const countPrescriptions = `-- name: CountPrescriptions :one
SELECT count(*) FROM prescriptions
WHERE branch_id = $1
  AND ($2::uuid IS NULL OR customer_id = $2)
`

type CountPrescriptionsParams struct {
	BranchID   uuid.UUID  `json:"branch_id"`
	CustomerID *uuid.UUID `json:"customer_id"`
}

func (q *Queries) CountPrescriptions(ctx context.Context, arg CountPrescriptionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPrescriptions, arg.BranchID, arg.CustomerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPrescription = `-- name: CreatePrescription :one
INSERT INTO prescriptions (customer_id, branch_id, doctor_name, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, customer_id, branch_id, doctor_name, notes, dispensed_at, created_at
`

type CreatePrescriptionParams struct {
	CustomerID uuid.UUID `json:"customer_id"`
	BranchID   uuid.UUID `json:"branch_id"`
	DoctorName string    `json:"doctor_name"`
	Notes      string    `json:"notes"`
}

func (q *Queries) CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (Prescription, error) {
	row := q.db.QueryRow(ctx, createPrescription,
		arg.CustomerID,
		arg.BranchID,
		arg.DoctorName,
		arg.Notes,
	)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.BranchID,
		&i.DoctorName,
		&i.Notes,
		&i.DispensedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPrescription = `-- name: GetPrescription :one
SELECT id, customer_id, branch_id, doctor_name, notes, dispensed_at, created_at FROM prescriptions WHERE id = $1
`

func (q *Queries) GetPrescription(ctx context.Context, id uuid.UUID) (Prescription, error) {
	row := q.db.QueryRow(ctx, getPrescription, id)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.BranchID,
		&i.DoctorName,
		&i.Notes,
		&i.DispensedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listPrescriptionItems = `-- name: ListPrescriptionItems :many
SELECT id, prescription_id, product_id, qty, dosage FROM prescription_items WHERE prescription_id = $1 ORDER BY id
`

func (q *Queries) ListPrescriptionItems(ctx context.Context, prescriptionID uuid.UUID) ([]PrescriptionItem, error) {
	rows, err := q.db.Query(ctx, listPrescriptionItems, prescriptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrescriptionItem{}
	for rows.Next() {
		var i PrescriptionItem
		if err := rows.Scan(
			&i.ID,
			&i.PrescriptionID,
			&i.ProductID,
			&i.Qty,
			&i.Dosage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptionItemsForPrescriptions = `-- name: ListPrescriptionItemsForPrescriptions :many
SELECT id, prescription_id, product_id, qty, dosage FROM prescription_items
WHERE prescription_id = ANY($1::uuid[])
ORDER BY prescription_id, id
`

// Batch item-load for a page of prescriptions (avoids an N+1 in the list).
func (q *Queries) ListPrescriptionItemsForPrescriptions(ctx context.Context, ids []uuid.UUID) ([]PrescriptionItem, error) {
	rows, err := q.db.Query(ctx, listPrescriptionItemsForPrescriptions, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PrescriptionItem{}
	for rows.Next() {
		var i PrescriptionItem
		if err := rows.Scan(
			&i.ID,
			&i.PrescriptionID,
			&i.ProductID,
			&i.Qty,
			&i.Dosage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrescriptions = `-- name: ListPrescriptions :many
SELECT id, customer_id, branch_id, doctor_name, notes, dispensed_at, created_at FROM prescriptions
WHERE branch_id = $1
  AND ($2::uuid IS NULL OR customer_id = $2)
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListPrescriptionsParams struct {
	BranchID   uuid.UUID  `json:"branch_id"`
	CustomerID *uuid.UUID `json:"customer_id"`
	Offset     int32      `json:"offset"`
	Limit      int32      `json:"limit"`
}

func (q *Queries) ListPrescriptions(ctx context.Context, arg ListPrescriptionsParams) ([]Prescription, error) {
	rows, err := q.db.Query(ctx, listPrescriptions,
		arg.BranchID,
		arg.CustomerID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prescription{}
	for rows.Next() {
		var i Prescription
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.BranchID,
			&i.DoctorName,
			&i.Notes,
			&i.DispensedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPrescriptionDispensed = `-- name: MarkPrescriptionDispensed :one
UPDATE prescriptions
SET dispensed_at = now()
WHERE id = $1 AND dispensed_at IS NULL
RETURNING id, customer_id, branch_id, doctor_name, notes, dispensed_at, created_at
`

// Mark a prescription dispensed once. The guard makes re-dispensing a no-op
// (0 rows), preventing a prescription from being filled twice.
func (q *Queries) MarkPrescriptionDispensed(ctx context.Context, id uuid.UUID) (Prescription, error) {
	row := q.db.QueryRow(ctx, markPrescriptionDispensed, id)
	var i Prescription
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.BranchID,
		&i.DoctorName,
		&i.Notes,
		&i.DispensedAt,
		&i.CreatedAt,
	)
	return i, err
}
