// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProducts = `-- name: CountProducts :one
SELECT count(*) FROM products
WHERE (
    $1::text IS NULL
    OR name ILIKE '%' || $1 || '%'
    OR generic_name ILIKE '%' || $1 || '%'
    OR barcode = $1
)
  AND ($2::text IS NULL OR category = $2)
  AND ($3::boolean IS NULL OR active = $3)
`

type CountProductsParams struct {
	Search   *string `json:"search"`
	Category *string `json:"category"`
	Active   *bool   `json:"active"`
}

func (q *Queries) CountProducts(ctx context.Context, arg CountProductsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProducts, arg.Search, arg.Category, arg.Active)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name, generic_name, form, strength, barcode, category, unit, reorder_level
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, generic_name, form, strength, barcode, category, unit, reorder_level, active, created_at, updated_at
`

type CreateProductParams struct {
	Name         string  `json:"name"`
	GenericName  string  `json:"generic_name"`
	Form         string  `json:"form"`
	Strength     string  `json:"strength"`
	Barcode      *string `json:"barcode"`
	Category     string  `json:"category"`
	Unit         string  `json:"unit"`
	ReorderLevel int32   `json:"reorder_level"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.GenericName,
		arg.Form,
		arg.Strength,
		arg.Barcode,
		arg.Category,
		arg.Unit,
		arg.ReorderLevel,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.Form,
		&i.Strength,
		&i.Barcode,
		&i.Category,
		&i.Unit,
		&i.ReorderLevel,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, generic_name, form, strength, barcode, category, unit, reorder_level, active, created_at, updated_at FROM products WHERE id = $1
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.Form,
		&i.Strength,
		&i.Barcode,
		&i.Category,
		&i.Unit,
		&i.ReorderLevel,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByBarcode = `-- name: GetProductByBarcode :one
SELECT id, name, generic_name, form, strength, barcode, category, unit, reorder_level, active, created_at, updated_at FROM products WHERE barcode = $1
`

func (q *Queries) GetProductByBarcode(ctx context.Context, barcode *string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByBarcode, barcode)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.Form,
		&i.Strength,
		&i.Barcode,
		&i.Category,
		&i.Unit,
		&i.ReorderLevel,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProductCategories = `-- name: ListProductCategories :many
SELECT DISTINCT category FROM products WHERE category <> '' ORDER BY category
`

func (q *Queries) ListProductCategories(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listProductCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var category string
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.name, p.generic_name, p.form, p.strength, p.barcode, p.category, p.unit, p.reorder_level, p.active, p.created_at, p.updated_at,
    COALESCE((
        SELECT SUM(sb.quantity) FROM stock_batches sb
        WHERE sb.product_id = p.id AND sb.branch_id = $1
    ), 0)::bigint AS on_hand
FROM products p
WHERE (
    $2::text IS NULL
    OR p.name ILIKE '%' || $2 || '%'
    OR p.generic_name ILIKE '%' || $2 || '%'
    OR p.barcode = $2
)
  AND ($3::text IS NULL OR p.category = $3)
  AND ($4::boolean IS NULL OR p.active = $4)
ORDER BY p.name
LIMIT $6 OFFSET $5
`

type ListProductsParams struct {
	BranchID *uuid.UUID `json:"branch_id"`
	Search   *string    `json:"search"`
	Category *string    `json:"category"`
	Active   *bool      `json:"active"`
	Offset   int32      `json:"offset"`
	Limit    int32      `json:"limit"`
}

type ListProductsRow struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	GenericName  string    `json:"generic_name"`
	Form         string    `json:"form"`
	Strength     string    `json:"strength"`
	Barcode      *string   `json:"barcode"`
	Category     string    `json:"category"`
	Unit         string    `json:"unit"`
	ReorderLevel int32     `json:"reorder_level"`
	Active       bool      `json:"active"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	OnHand       int64     `json:"on_hand"`
}

// on_hand is the stock at the given branch (0 when branch_id is null).
func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.BranchID,
		arg.Search,
		arg.Category,
		arg.Active,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsRow{}
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GenericName,
			&i.Form,
			&i.Strength,
			&i.Barcode,
			&i.Category,
			&i.Unit,
			&i.ReorderLevel,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OnHand,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET name = $2, generic_name = $3, form = $4, strength = $5,
    barcode = $6, category = $7, unit = $8, reorder_level = $9,
    active = $10, updated_at = now()
WHERE id = $1
RETURNING id, name, generic_name, form, strength, barcode, category, unit, reorder_level, active, created_at, updated_at
`

type UpdateProductParams struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	GenericName  string    `json:"generic_name"`
	Form         string    `json:"form"`
	Strength     string    `json:"strength"`
	Barcode      *string   `json:"barcode"`
	Category     string    `json:"category"`
	Unit         string    `json:"unit"`
	ReorderLevel int32     `json:"reorder_level"`
	Active       bool      `json:"active"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.GenericName,
		arg.Form,
		arg.Strength,
		arg.Barcode,
		arg.Category,
		arg.Unit,
		arg.ReorderLevel,
		arg.Active,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GenericName,
		&i.Form,
		&i.Strength,
		&i.Barcode,
		&i.Category,
		&i.Unit,
		&i.ReorderLevel,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
