// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchase.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const addPurchaseOrderItem = `-- name: AddPurchaseOrderItem :one
INSERT INTO purchase_order_items (po_id, product_id, qty, unit_cost)
VALUES ($1, $2, $3, $4)
RETURNING id, po_id, product_id, qty, unit_cost
`

type AddPurchaseOrderItemParams struct {
	PoID      uuid.UUID       `json:"po_id"`
	ProductID uuid.UUID       `json:"product_id"`
	Qty       int32           `json:"qty"`
	UnitCost  decimal.Decimal `json:"unit_cost"`
}

func (q *Queries) AddPurchaseOrderItem(ctx context.Context, arg AddPurchaseOrderItemParams) (PurchaseOrderItem, error) {
	row := q.db.QueryRow(ctx, addPurchaseOrderItem,
		arg.PoID,
		arg.ProductID,
		arg.Qty,
		arg.UnitCost,
	)
	var i PurchaseOrderItem
	err := row.Scan(
		&i.ID,
		&i.PoID,
		&i.ProductID,
		&i.Qty,
		&i.UnitCost,
	)
	return i, err
}

const countPurchaseOrders = `-- name: CountPurchaseOrders :one
SELECT count(*) FROM purchase_orders WHERE branch_id = $1
`

func (q *Queries) CountPurchaseOrders(ctx context.Context, branchID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseOrders, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (branch_id, supplier_id, reference, status, ordered_at)
VALUES ($1, $2, $3, 'ordered', now())
RETURNING id, branch_id, supplier_id, status, reference, ordered_at, received_at, created_at, updated_at
`

type CreatePurchaseOrderParams struct {
	BranchID   uuid.UUID `json:"branch_id"`
	SupplierID uuid.UUID `json:"supplier_id"`
	Reference  string    `json:"reference"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder, arg.BranchID, arg.SupplierID, arg.Reference)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.SupplierID,
		&i.Status,
		&i.Reference,
		&i.OrderedAt,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT id, branch_id, supplier_id, status, reference, ordered_at, received_at, created_at, updated_at FROM purchase_orders WHERE id = $1
`

func (q *Queries) GetPurchaseOrder(ctx context.Context, id uuid.UUID) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, id)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.SupplierID,
		&i.Status,
		&i.Reference,
		&i.OrderedAt,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPurchaseOrderItems = `-- name: ListPurchaseOrderItems :many
SELECT id, po_id, product_id, qty, unit_cost FROM purchase_order_items WHERE po_id = $1 ORDER BY id
`

func (q *Queries) ListPurchaseOrderItems(ctx context.Context, poID uuid.UUID) ([]PurchaseOrderItem, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderItems, poID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseOrderItem{}
	for rows.Next() {
		var i PurchaseOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.PoID,
			&i.ProductID,
			&i.Qty,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrderItemsForOrders = `-- name: ListPurchaseOrderItemsForOrders :many
SELECT id, po_id, product_id, qty, unit_cost FROM purchase_order_items
WHERE po_id = ANY($1::uuid[])
ORDER BY po_id, id
`

// Batch item-load for a page of orders (avoids an N+1 in the list endpoint).
func (q *Queries) ListPurchaseOrderItemsForOrders(ctx context.Context, poIds []uuid.UUID) ([]PurchaseOrderItem, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrderItemsForOrders, poIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseOrderItem{}
	for rows.Next() {
		var i PurchaseOrderItem
		if err := rows.Scan(
			&i.ID,
			&i.PoID,
			&i.ProductID,
			&i.Qty,
			&i.UnitCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT id, branch_id, supplier_id, status, reference, ordered_at, received_at, created_at, updated_at FROM purchase_orders
WHERE branch_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPurchaseOrdersParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]PurchaseOrder, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders, arg.BranchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseOrder{}
	for rows.Next() {
		var i PurchaseOrder
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.SupplierID,
			&i.Status,
			&i.Reference,
			&i.OrderedAt,
			&i.ReceivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPurchaseOrderReceived = `-- name: MarkPurchaseOrderReceived :one
UPDATE purchase_orders
SET status = 'received', received_at = now(), updated_at = now()
WHERE id = $1 AND status <> 'received'
RETURNING id, branch_id, supplier_id, status, reference, ordered_at, received_at, created_at, updated_at
`

// Mark a PO received. The status guard makes double-receipt a no-op (0 rows),
// so stock is never added twice for the same order.
func (q *Queries) MarkPurchaseOrderReceived(ctx context.Context, id uuid.UUID) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, markPurchaseOrderReceived, id)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.SupplierID,
		&i.Status,
		&i.Reference,
		&i.OrderedAt,
		&i.ReceivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
