// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddPrescriptionItem(ctx context.Context, arg AddPrescriptionItemParams) (PrescriptionItem, error)
	AddPurchaseOrderItem(ctx context.Context, arg AddPurchaseOrderItemParams) (PurchaseOrderItem, error)
	AddSaleItem(ctx context.Context, arg AddSaleItemParams) (SaleItem, error)
	// Apply a signed delta to a batch, refusing to drive quantity negative.
	// Zero rows returned means the adjustment would go below zero.
	AdjustBatchQuantity(ctx context.Context, arg AdjustBatchQuantityParams) (StockBatch, error)
	CountBranchBatches(ctx context.Context, branchID uuid.UUID) (int64, error)
	CountBranches(ctx context.Context) (int64, error)
	CountCustomers(ctx context.Context, search *string) (int64, error)
	CountPrescriptions(ctx context.Context, branchID uuid.UUID) (int64, error)
	CountProducts(ctx context.Context, search *string) (int64, error)
	CountPurchaseOrders(ctx context.Context, branchID uuid.UUID) (int64, error)
	CountSales(ctx context.Context, branchID uuid.UUID) (int64, error)
	CountStockMovements(ctx context.Context, arg CountStockMovementsParams) (int64, error)
	CountSuppliers(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreatePrescription(ctx context.Context, arg CreatePrescriptionParams) (Prescription, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	// Inventory write queries. Batches and the movement ledger are written by the
	// purchasing (goods-received) and sales (dispensing) flows inside a transaction.
	CreateStockBatch(ctx context.Context, arg CreateStockBatchParams) (StockBatch, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Decrement a batch's quantity, but only if enough remains. Returns the updated
	// row; zero rows means insufficient stock (used by FEFO dispensing).
	DecrementBatchQuantity(ctx context.Context, arg DecrementBatchQuantityParams) (StockBatch, error)
	GetBranch(ctx context.Context, id uuid.UUID) (Branch, error)
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	GetPrescription(ctx context.Context, id uuid.UUID) (Prescription, error)
	GetProduct(ctx context.Context, id uuid.UUID) (Product, error)
	GetPurchaseOrder(ctx context.Context, id uuid.UUID) (PurchaseOrder, error)
	GetSale(ctx context.Context, id uuid.UUID) (Sale, error)
	// Stock adjustment / return writes and the movement-ledger view ---------------
	GetStockBatch(ctx context.Context, id uuid.UUID) (StockBatch, error)
	GetSupplier(ctx context.Context, id uuid.UUID) (Supplier, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InventoryValuation(ctx context.Context, branchID uuid.UUID) (InventoryValuationRow, error)
	// Inventory read queries (per-branch stock, expiry & reorder alerts) ----------
	ListBranchBatches(ctx context.Context, arg ListBranchBatchesParams) ([]ListBranchBatchesRow, error)
	ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	// FEFO: batches with stock for a product at a branch, earliest expiry first,
	// skipping already-expired stock. Locked FOR UPDATE so concurrent sales cannot
	// oversell the same batch.
	ListDispensableBatches(ctx context.Context, arg ListDispensableBatchesParams) ([]StockBatch, error)
	ListLowStock(ctx context.Context, branchID uuid.UUID) ([]ListLowStockRow, error)
	ListNearExpiryBatches(ctx context.Context, arg ListNearExpiryBatchesParams) ([]ListNearExpiryBatchesRow, error)
	ListPrescriptionItems(ctx context.Context, prescriptionID uuid.UUID) ([]PrescriptionItem, error)
	ListPrescriptions(ctx context.Context, arg ListPrescriptionsParams) ([]Prescription, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListPurchaseOrderItems(ctx context.Context, poID uuid.UUID) ([]PurchaseOrderItem, error)
	ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]PurchaseOrder, error)
	// Ordered by the dispensed batch's expiry (FEFO / dispensing order), with id as
	// a stable tie-breaker, so receipt line items appear deterministically.
	ListSaleItems(ctx context.Context, saleID uuid.UUID) ([]SaleItem, error)
	ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error)
	ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]ListStockMovementsRow, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Mark a prescription dispensed once. The guard makes re-dispensing a no-op
	// (0 rows), preventing a prescription from being filled twice.
	MarkPrescriptionDispensed(ctx context.Context, id uuid.UUID) (Prescription, error)
	// Mark a PO received. The status guard makes double-receipt a no-op (0 rows),
	// so stock is never added twice for the same order.
	MarkPurchaseOrderReceived(ctx context.Context, id uuid.UUID) (PurchaseOrder, error)
	// A trivial query used to verify database connectivity and the query pipeline.
	Now(ctx context.Context) (time.Time, error)
	RecordStockMovement(ctx context.Context, arg RecordStockMovementParams) (StockMovement, error)
	SalesDaily(ctx context.Context, arg SalesDailyParams) ([]SalesDailyRow, error)
	SalesSummary(ctx context.Context, arg SalesSummaryParams) (SalesSummaryRow, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	StockOnHand(ctx context.Context, arg StockOnHandParams) (int64, error)
	// Total units already returned to a given batch against a given sale. Used to
	// cap sale-linked returns at the quantity actually dispensed.
	SumReturnedForSaleBatch(ctx context.Context, arg SumReturnedForSaleBatchParams) (int64, error)
	TopSellingProducts(ctx context.Context, arg TopSellingProductsParams) ([]TopSellingProductsRow, error)
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
