// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	AddPurchaseOrderItem(ctx context.Context, arg AddPurchaseOrderItemParams) (PurchaseOrderItem, error)
	AddSaleItem(ctx context.Context, arg AddSaleItemParams) (SaleItem, error)
	CountBranchBatches(ctx context.Context, branchID uuid.UUID) (int64, error)
	CountBranches(ctx context.Context) (int64, error)
	CountProducts(ctx context.Context, search *string) (int64, error)
	CountPurchaseOrders(ctx context.Context, branchID uuid.UUID) (int64, error)
	CountSales(ctx context.Context, branchID uuid.UUID) (int64, error)
	CountSuppliers(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	// Inventory write queries. Batches and the movement ledger are written by the
	// purchasing (goods-received) and sales (dispensing) flows inside a transaction.
	CreateStockBatch(ctx context.Context, arg CreateStockBatchParams) (StockBatch, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Decrement a batch's quantity, but only if enough remains. Returns the updated
	// row; zero rows means insufficient stock (used by FEFO dispensing).
	DecrementBatchQuantity(ctx context.Context, arg DecrementBatchQuantityParams) (StockBatch, error)
	GetBranch(ctx context.Context, id uuid.UUID) (Branch, error)
	GetProduct(ctx context.Context, id uuid.UUID) (Product, error)
	GetPurchaseOrder(ctx context.Context, id uuid.UUID) (PurchaseOrder, error)
	GetSale(ctx context.Context, id uuid.UUID) (Sale, error)
	GetSupplier(ctx context.Context, id uuid.UUID) (Supplier, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Inventory read queries (per-branch stock, expiry & reorder alerts) ----------
	ListBranchBatches(ctx context.Context, arg ListBranchBatchesParams) ([]ListBranchBatchesRow, error)
	ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error)
	// FEFO: batches with stock for a product at a branch, earliest expiry first,
	// skipping already-expired stock. Locked FOR UPDATE so concurrent sales cannot
	// oversell the same batch.
	ListDispensableBatches(ctx context.Context, arg ListDispensableBatchesParams) ([]StockBatch, error)
	ListLowStock(ctx context.Context, branchID uuid.UUID) ([]ListLowStockRow, error)
	ListNearExpiryBatches(ctx context.Context, arg ListNearExpiryBatchesParams) ([]ListNearExpiryBatchesRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListPurchaseOrderItems(ctx context.Context, poID uuid.UUID) ([]PurchaseOrderItem, error)
	ListPurchaseOrders(ctx context.Context, arg ListPurchaseOrdersParams) ([]PurchaseOrder, error)
	ListSaleItems(ctx context.Context, saleID uuid.UUID) ([]SaleItem, error)
	ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Mark a PO received. The status guard makes double-receipt a no-op (0 rows),
	// so stock is never added twice for the same order.
	MarkPurchaseOrderReceived(ctx context.Context, id uuid.UUID) (PurchaseOrder, error)
	// A trivial query used to verify database connectivity and the query pipeline.
	Now(ctx context.Context) (time.Time, error)
	RecordStockMovement(ctx context.Context, arg RecordStockMovementParams) (StockMovement, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error
	StockOnHand(ctx context.Context, arg StockOnHandParams) (int64, error)
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
