// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const inventoryValuation = `-- name: InventoryValuation :one
SELECT
    COALESCE(SUM(quantity), 0)::bigint               AS total_units,
    COALESCE(SUM(quantity * cost_price), 0)::numeric AS cost_value,
    COALESCE(SUM(quantity * sale_price), 0)::numeric AS retail_value
FROM stock_batches
WHERE branch_id = $1
`

type InventoryValuationRow struct {
	TotalUnits  int64           `json:"total_units"`
	CostValue   decimal.Decimal `json:"cost_value"`
	RetailValue decimal.Decimal `json:"retail_value"`
}

func (q *Queries) InventoryValuation(ctx context.Context, branchID uuid.UUID) (InventoryValuationRow, error) {
	row := q.db.QueryRow(ctx, inventoryValuation, branchID)
	var i InventoryValuationRow
	err := row.Scan(&i.TotalUnits, &i.CostValue, &i.RetailValue)
	return i, err
}

const salesByPayment = `-- name: SalesByPayment :many
SELECT
    payment_method,
    count(*)::bigint                 AS sale_count,
    COALESCE(SUM(total), 0)::numeric AS revenue
FROM sales
WHERE branch_id = $1
  AND created_at >= $2 AND created_at < $3
  AND voided_at IS NULL
GROUP BY payment_method
ORDER BY revenue DESC
`

type SalesByPaymentParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	From     time.Time `json:"from"`
	To       time.Time `json:"to"`
}

type SalesByPaymentRow struct {
	PaymentMethod PaymentMethod   `json:"payment_method"`
	SaleCount     int64           `json:"sale_count"`
	Revenue       decimal.Decimal `json:"revenue"`
}

func (q *Queries) SalesByPayment(ctx context.Context, arg SalesByPaymentParams) ([]SalesByPaymentRow, error) {
	rows, err := q.db.Query(ctx, salesByPayment, arg.BranchID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByPaymentRow{}
	for rows.Next() {
		var i SalesByPaymentRow
		if err := rows.Scan(&i.PaymentMethod, &i.SaleCount, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesDaily = `-- name: SalesDaily :many
SELECT
    (date_trunc('day', created_at))::date AS day,
    count(*)::bigint                      AS sale_count,
    COALESCE(SUM(total), 0)::numeric      AS revenue
FROM sales
WHERE branch_id = $1 AND created_at >= $2 AND created_at < $3
GROUP BY day
ORDER BY day
`

type SalesDailyParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	From     time.Time `json:"from"`
	To       time.Time `json:"to"`
}

type SalesDailyRow struct {
	Day       time.Time       `json:"day"`
	SaleCount int64           `json:"sale_count"`
	Revenue   decimal.Decimal `json:"revenue"`
}

func (q *Queries) SalesDaily(ctx context.Context, arg SalesDailyParams) ([]SalesDailyRow, error) {
	rows, err := q.db.Query(ctx, salesDaily, arg.BranchID, arg.From, arg.To)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesDailyRow{}
	for rows.Next() {
		var i SalesDailyRow
		if err := rows.Scan(&i.Day, &i.SaleCount, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesSummary = `-- name: SalesSummary :one
SELECT
    count(*)::bigint                    AS sale_count,
    COALESCE(SUM(total), 0)::numeric    AS revenue,
    COALESCE(SUM(discount), 0)::numeric AS discount_total
FROM sales
WHERE branch_id = $1 AND created_at >= $2 AND created_at < $3
`

type SalesSummaryParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	From     time.Time `json:"from"`
	To       time.Time `json:"to"`
}

type SalesSummaryRow struct {
	SaleCount     int64           `json:"sale_count"`
	Revenue       decimal.Decimal `json:"revenue"`
	DiscountTotal decimal.Decimal `json:"discount_total"`
}

func (q *Queries) SalesSummary(ctx context.Context, arg SalesSummaryParams) (SalesSummaryRow, error) {
	row := q.db.QueryRow(ctx, salesSummary, arg.BranchID, arg.From, arg.To)
	var i SalesSummaryRow
	err := row.Scan(&i.SaleCount, &i.Revenue, &i.DiscountTotal)
	return i, err
}

const topSellingProducts = `-- name: TopSellingProducts :many
SELECT
    si.product_id,
    p.name                                     AS product_name,
    SUM(si.qty)::bigint                        AS units_sold,
    COALESCE(SUM(si.qty * si.unit_price), 0)::numeric AS revenue
FROM sale_items si
JOIN sales s    ON s.id = si.sale_id
JOIN products p ON p.id = si.product_id
WHERE s.branch_id = $1 AND s.created_at >= $2 AND s.created_at < $3
GROUP BY si.product_id, p.name
ORDER BY units_sold DESC
LIMIT $4
`

type TopSellingProductsParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	From     time.Time `json:"from"`
	To       time.Time `json:"to"`
	Limit    int32     `json:"limit"`
}

type TopSellingProductsRow struct {
	ProductID   uuid.UUID       `json:"product_id"`
	ProductName string          `json:"product_name"`
	UnitsSold   int64           `json:"units_sold"`
	Revenue     decimal.Decimal `json:"revenue"`
}

func (q *Queries) TopSellingProducts(ctx context.Context, arg TopSellingProductsParams) ([]TopSellingProductsRow, error) {
	rows, err := q.db.Query(ctx, topSellingProducts,
		arg.BranchID,
		arg.From,
		arg.To,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TopSellingProductsRow{}
	for rows.Next() {
		var i TopSellingProductsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.UnitsSold,
			&i.Revenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
