// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sale.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const addSaleItem = `-- name: AddSaleItem :one
INSERT INTO sale_items (sale_id, batch_id, product_id, qty, unit_price)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, sale_id, batch_id, product_id, qty, unit_price
`

type AddSaleItemParams struct {
	SaleID    uuid.UUID       `json:"sale_id"`
	BatchID   uuid.UUID       `json:"batch_id"`
	ProductID uuid.UUID       `json:"product_id"`
	Qty       int32           `json:"qty"`
	UnitPrice decimal.Decimal `json:"unit_price"`
}

func (q *Queries) AddSaleItem(ctx context.Context, arg AddSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, addSaleItem,
		arg.SaleID,
		arg.BatchID,
		arg.ProductID,
		arg.Qty,
		arg.UnitPrice,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.BatchID,
		&i.ProductID,
		&i.Qty,
		&i.UnitPrice,
	)
	return i, err
}

const countSales = `-- name: CountSales :one
SELECT count(*) FROM sales WHERE branch_id = $1
`

func (q *Queries) CountSales(ctx context.Context, branchID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSales, branchID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSale = `-- name: CreateSale :one
INSERT INTO sales (
    branch_id, cashier_id, customer_id, prescription_id,
    subtotal, discount, total, paid, payment_method
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, branch_id, cashier_id, customer_id, prescription_id, subtotal, discount, total, paid, payment_method, created_at
`

type CreateSaleParams struct {
	BranchID       uuid.UUID       `json:"branch_id"`
	CashierID      uuid.UUID       `json:"cashier_id"`
	CustomerID     *uuid.UUID      `json:"customer_id"`
	PrescriptionID *uuid.UUID      `json:"prescription_id"`
	Subtotal       decimal.Decimal `json:"subtotal"`
	Discount       decimal.Decimal `json:"discount"`
	Total          decimal.Decimal `json:"total"`
	Paid           decimal.Decimal `json:"paid"`
	PaymentMethod  PaymentMethod   `json:"payment_method"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.BranchID,
		arg.CashierID,
		arg.CustomerID,
		arg.PrescriptionID,
		arg.Subtotal,
		arg.Discount,
		arg.Total,
		arg.Paid,
		arg.PaymentMethod,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CashierID,
		&i.CustomerID,
		&i.PrescriptionID,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.Paid,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getSale = `-- name: GetSale :one
SELECT id, branch_id, cashier_id, customer_id, prescription_id, subtotal, discount, total, paid, payment_method, created_at FROM sales WHERE id = $1
`

func (q *Queries) GetSale(ctx context.Context, id uuid.UUID) (Sale, error) {
	row := q.db.QueryRow(ctx, getSale, id)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.BranchID,
		&i.CashierID,
		&i.CustomerID,
		&i.PrescriptionID,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.Paid,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const listSaleItems = `-- name: ListSaleItems :many
SELECT id, sale_id, batch_id, product_id, qty, unit_price FROM sale_items WHERE sale_id = $1 ORDER BY id
`

func (q *Queries) ListSaleItems(ctx context.Context, saleID uuid.UUID) ([]SaleItem, error) {
	rows, err := q.db.Query(ctx, listSaleItems, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SaleItem{}
	for rows.Next() {
		var i SaleItem
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.BatchID,
			&i.ProductID,
			&i.Qty,
			&i.UnitPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT id, branch_id, cashier_id, customer_id, prescription_id, subtotal, discount, total, paid, payment_method, created_at FROM sales
WHERE branch_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSalesParams struct {
	BranchID uuid.UUID `json:"branch_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]Sale, error) {
	rows, err := q.db.Query(ctx, listSales, arg.BranchID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Sale{}
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.CashierID,
			&i.CustomerID,
			&i.PrescriptionID,
			&i.Subtotal,
			&i.Discount,
			&i.Total,
			&i.Paid,
			&i.PaymentMethod,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
