// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supplier.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countSuppliers = `-- name: CountSuppliers :one
SELECT count(*) FROM suppliers
`

func (q *Queries) CountSuppliers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSuppliers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (name, contact, phone, email)
VALUES ($1, $2, $3, $4)
RETURNING id, name, contact, phone, email, active, created_at, updated_at
`

type CreateSupplierParams struct {
	Name    string `json:"name"`
	Contact string `json:"contact"`
	Phone   string `json:"phone"`
	Email   string `json:"email"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.Name,
		arg.Contact,
		arg.Phone,
		arg.Email,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Phone,
		&i.Email,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, name, contact, phone, email, active, created_at, updated_at FROM suppliers WHERE id = $1
`

func (q *Queries) GetSupplier(ctx context.Context, id uuid.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Phone,
		&i.Email,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, contact, phone, email, active, created_at, updated_at FROM suppliers
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListSuppliersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Contact,
			&i.Phone,
			&i.Email,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET name = $2, contact = $3, phone = $4, email = $5, active = $6, updated_at = now()
WHERE id = $1
RETURNING id, name, contact, phone, email, active, created_at, updated_at
`

type UpdateSupplierParams struct {
	ID      uuid.UUID `json:"id"`
	Name    string    `json:"name"`
	Contact string    `json:"contact"`
	Phone   string    `json:"phone"`
	Email   string    `json:"email"`
	Active  bool      `json:"active"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.ID,
		arg.Name,
		arg.Contact,
		arg.Phone,
		arg.Email,
		arg.Active,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Contact,
		&i.Phone,
		&i.Email,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
